version: '3.8'

networks:
  pocketploy-network:
    external: true

services:
  traefik:
    image: traefik:v3.0
    container_name: pocketploy-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml:ro
    networks:
      - pocketploy-network
    labels:
      - "traefik.enable=true"